name: New changes validation

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  cache-V:
    runs-on: ubuntu-latest
    steps:
      - name: Check if V is cached
        id: check-v-cache
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08

      - if: ${{ steps.check-v-cache.outputs.cache-hit != 'true' }}
        name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - if: ${{ steps.check-v-cache.outputs.cache-hit != 'true' }}
        name: Cache Vlang
        uses: actions/cache/save@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08

  simple-build:
    needs: cache-V
    runs-on: ubuntu-latest
    strategy:
      matrix:
        trimming: [ null , -skip-unused ]
        memory-management: [ null , -autofree ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: ${{ matrix.trimming }} ${{ matrix.memory-management }} build
        run: v ${{ matrix.trimming }} ${{ matrix.memory-management }} .

  tests:
    needs: simple-build
    runs-on: ubuntu-latest
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Run tests
        run: v test .

  cache-clang:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if LLVM and Clang is cached
        id: check-llvm-cache
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15

      - if: ${{ steps.check-llvm-cache.outputs.cache-hit != 'true' }}
        name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'

      - if: ${{ steps.check-llvm-cache.outputs.cache-hit != 'true' }}
        name: Cache LLVM and Clang
        uses: actions/cache/save@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15

  different-compilers:
    needs: cache-clang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        trimming: [ null , -skip-unused ]
        memory-management: [ null , -autofree ]
        optimization: [ null , -prod ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - if: ${{ matrix.compiler == 'gcc' }}
        name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - if: ${{ matrix.compiler == 'clang' }}
        name: Restore LLVM and Clang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15
          fail-on-cache-miss: true

      - if: ${{ matrix.compiler == 'clang' }}
        name: Setup LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'
          cached: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: ${{ matrix.compiler }} ${{ matrix.trimming }} ${{ matrix.optimization }} ${{ matrix.memory-management }} build
        run: v -cc ${{ matrix.compiler }} ${{ matrix.trimming }} ${{ matrix.optimization }} ${{ matrix.memory-management }} .

  clang-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [ address, thread, memory, undefined, leak ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Restore LLVM and Clang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/llvm
          key: llvm-15
          fail-on-cache-miss: true

      - name: Setup LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'
          cached: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Clang ${{ matrix.sanitizer }} sanitizer
        run: v -cc clang -cflags -fsanitize=${{ matrix.sanitizer }} .

  gcc-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [ thread, leak ]
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC ${{ matrix.sanitizer }} sanitizer
        run: v -cc gcc -cflags -fsanitize=${{ matrix.sanitizer }} .

  gcc-address-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC address sanitizer ${{ matrix.dependent-sanitizer }}
        run: v -cc gcc -cflags -fsanitize=address -cflags -fsanitize-address-use-after-scope \
             -cflags -fsanitize=pointer-compare \
             -cflags -fsanitize=pointer-subtract \
             .

  gcc-undefined-sanitizers:
    needs: different-compilers
    runs-on: ubuntu-latest
    steps:
      - name: Restore Vlang
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/v-project-basement/v-project-basement/vlang/
          key: vlang-0.3.3-weekly.2023.08
          fail-on-cache-miss: true

      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          version: 'weekly.2023.08'

      - name: Set up GCC
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y build-essential

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: GCC undefined sanitizer ${{ matrix.dependent-sanitizer }}
        run: v -cc gcc -cflags -fsanitize=undefined \
             -cflags -fsanitize=shift \
             -cflags -fsanitize=shift-exponent \
             -cflags -fsanitize=shift-base \
             -cflags -fsanitize=integer-divide-by-zero \
             -cflags -fsanitize=unreachable \
             -cflags -fsanitize=vla-bound \
             -cflags -fsanitize=null \
             -cflags -fsanitize=return \
             -cflags -fsanitize=signed-integer-overflow \
             -cflags -fsanitize=bounds \
             -cflags -fsanitize=bounds-strict \
             -cflags -fsanitize=alignment \
             -cflags -fsanitize=object-size \
             -cflags -fsanitize=float-divide-by-zero \
             -cflags -fsanitize=float-cast-overflow \
             -cflags -fsanitize=nonnull-attribute \
             -cflags -fsanitize=returns-nonnull-attribute \
             -cflags -fsanitize=bool \
             -cflags -fsanitize=enum \
             -cflags -fsanitize=vptr \
             -cflags -fsanitize=pointer-overflow \
             -cflags -fsanitize=builtin \
             .
